### ISSUE TITLE
resume run from appropriate element when analyser is interrupted

### ISSUE THREAD

**Issue by breezykermo** [forensic-architecture/mtriage#10]
It should be mtriage's responsibility to work out (based on a comparison of output and input folders), when an analyser is being run from scratch and when it is being resumed. If it is being resumed, it should not re-run analysis on elements that have already been analysed.

**Comment by RaphiePS** [comment]
This is a bit tricky in the case where an analyser is killed mid-processing. For instance, say the `FramesAnalyser` is interrupted halfway through converting a video element to frames. It will have already created an output folder and saved half the frames into it. But there's no indication of whether it's actually finished - without extra information, there's no way to know whether it's saved *all* the frames.

Three possible approaches off the top of my head:
1) Analysers name their output folders `[elementname]_inprogress`, and rename the folder once actually finished.
2) Analysers place a special, empty `DONE` file in the output folder once finished. No folder renaming shenanigans.
3) Analysers call a special method indicating they're done, which updates a JSON file or SQLite database that keeps track of pending and completed tasks.

Option 1 seems a little hacky, and Option 3 appears overly complex. Option 2 is simple enough, but might cause issues if further processing stages don't check extensions and expect everything in an output folder to be a valid file, thereby tripping up on `DONE`. Let me know what you think - do any of these appeal to you, or perhaps a better approach?

**Comment by breezykermo** [comment]
Hi @RaphiePS, welcome. Because the analyser currently runs elements sequentially (no parallelisation), the v0 implementation that I was imagining is to resume analysis from the "last" element processed by providing a check before an element is analysed to consider whether the expected output element exists, and restarting the analysis by just redoing the _last_ element with an expected output element and continuing. This is admittedly frail, for two reasons:

1. It assumes seriality, and so won't hold up when analysis is parallelised/multithreaded (a feature that is intended in the near future).
2. Currently, the analyser base class exposes a [run method](https://github.com/forensic-architecture/mtriage/blob/master/src/lib/common/analyser.py#L117-L122) that doesn't encapsulate the iterative logic, and so it is necessary to [duplicate it in analyser implementations](https://github.com/forensic-architecture/mtriage/blob/master/src/lib/analysers/frames/main.py#L22-L24).

To address the first point, I think we ultimately do want to move towards a simple version of your suggested 3rd solution. The selector base class does something along these lines in creating a [`SELECT_MAP`](https://github.com/forensic-architecture/mtriage/blob/master/src/lib/common/selector.py#L27) which maps the elements that a folder produced from the youtube selector contains. In the selector's case this map is necessary, as the handler that maps the space to select (the [index](https://github.com/forensic-architecture/mtriage/blob/master/src/lib/common/selector.py#L45-L54) method)  is often different from the handler that creates the elements by downloading the media ([retrieve_row](https://github.com/forensic-architecture/mtriage/blob/master/src/lib/common/selector.py#L72-L88)).

So I think the first step towards this is to code a solution for issue #2, then to create a more robust `ANALYSER_MAP` file that is modelled on `SELECTOR_MAP`, and _then_ to put the appropriate checks in `run_element` to close this issue. 

Would you like to have a go at #2? If not I should be able to get to it at the end of this week. Thanks for your help here, much appreciated!

**Comment by breezykermo** [comment]
Sorry, accidentally closed..

**Comment by RaphiePS** [comment]
On it! The resume-from-last-element trick is really clever (I like that it avoids storing extra information), but I agree: this is crying out for some parallelism. Will likely have a few questions as I figure out how everything fits together, but seems pretty doable 👍

**Comment by RaphiePS** [comment]
After poking around the codebase, I get the feeling that the resume logic will be pretty intertwined with the parallel-processing setup. It might make sense to just knock them both out in one go, rather than writing a resume feature that will need to be altered later on. I've got some availability this week, and if you think the time is right, I'd be delighted to take 'em both on. 

Some thoughts on the parallel problem - of course, I'd defer to you on the implementation, but here's how I'd approach it in general:

- Create a superclass for both `Selector` and `Analyser` that encapsulates all this indexing/parallel-processing/logging/resuming functionality. Both `Selector` and `Analyser` need to follow roughly the same steps (figure out what needs to be done, do that in parallel, and record it being done), and that code could be shared in a `Processor` superclass. 

- Python's GIL means multithreaded code isn't actually running in parallel 😠We'd probably want to use `multiprocessing`. It's much harder to communicate between these workers (no shared memory), but as you said, these tasks are embarrassingly parallel; they shouldn't really need to communicate anyway.

- I'd probably move from CSV map files to SQLite. With multiple processes reading and writing to the map file, things could get pretty dicey without synchronization. SQLite handles all that for you, letting you read and write without locking the file. I've quite enjoyed using [dataset](https://dataset.readthedocs.io/en/latest/) for this sort of thing. It's at a happy medium between "write all your SQL queries by hand" and "deal with a massively bloated ORM."

- Resumable + parallel job scheduling is a pretty common problem, and there might be an existing library that solves it well and adds other goodies. I've seen a lot of Redis-based frameworks, but that would be overkill. I'll see if I can find a simpler solution that would be easy to integrate.

**Comment by breezykermo** [comment]
Continuing this thread on parallelisation on #30. I agree with you: if we are going with solution 3 from your original suggested solutions, then it makes sense to address #30 before returning here.

**Comment by breezykermo** [comment]
Handling this as part of submitting a PR for #30
