### ISSUE TITLE
get_selector/analyser should pull list of selectors/analysers from json file

### ISSUE THREAD

**Issue by samludford** [forensic-architecture/mtriage#34]
The get_analyser and get_selector files currently hard code the names and types of specific analysers and selectors. This will cause problems for future development of partial build capabilities - instead these values should be stored in a json file and loaded dynamically.

**Comment by breezykermo** [comment]
Bumping this to release, as it actually causes the Travis `python run.py test` to fail due to having to import the `YoutubeSelector`, which then wants credential files that Travis doesn't have.

**Comment by breezykermo** [comment]
Additionally in this issue, we should address the fact that Travis currently doesn't report a failed build if `python run.py test` has failing tests. This is due to the way that the tests are run via 'run.py': the error is not raised to the Travis console, and so Travis thinks that the command `python run.py test` has run appropriately.
