### ISSUE TITLE
explicit type declarations in common

### ISSUE THREAD

**Issue by breezykermo** [forensic-architecture/mtriage#43]
Python 3 has [typing support](https://docs.python.org/3/library/typing.html) -- we should use it in the common code, especially for the methods that are made available on selector and analysers.

**Comment by jamesb93** [comment]
Hi @breezykermo ,

I came to mtriage via the Triple Chaser video. Curiosity got the better of me and here I am.

I started implementing types for common on my fork under the branch 'typing': https://github.com/jamesb93/mtriage/tree/typing

Perhaps you can advise me what a `config` is? https://github.com/forensic-architecture/mtriage/blob/d7e4a84a22930430346e6bff3ccffe12dc16960d/src/lib/common/analyser.py#L55 so that I can finish typing for the analysers. Also, it'd be nice if you could review the types I did set as some of them are likely to be wrong from my misunderstanding of the code.

Thanks!

**Comment by breezykermo** [comment]
Hiya! Thanks for your interest.

A `config` is an object returned from pyyaml's `yaml.safe_load`, which is validated at runtime according to the flexible structure detailed in [this PR](https://github.com/forensic-architecture/mtriage/pull/123). There should be documentation for this beyond the comments in this PR, but unfortunately I don't think there is yet.

**Comment by breezykermo** [comment]
You can find the relevant code for validating the YAML object in [src/validate.py](https://github.com/forensic-architecture/mtriage/blob/master/src/validate.py), which is invoked at runtime [here in run.py](https://github.com/forensic-architecture/mtriage/blob/master/src/run.py#L38).

**Comment by breezykermo** [comment]
Closing this, as with the rewrite from a few months ago I believe this was mostly covered.
