### ISSUE TITLE
better failure protocol for retrieve_element and analyse_element

### ISSUE THREAD

**Issue by breezykermo** [forensic-architecture/mtriage#51]
I've been thinking that another protocol we need around well-built selectors/analysers is what to do when `retrieve_element` or `analyse_element` fails in some way. Currently, when there is an error in a single element, the entire process collapses, which is not what we want.

In `youtube`, for example, when a download fails we essentially want to just skip the element and keep going. Similarly in `frames`, if something happens, we essentially want to just keep going, or potentially to restart `analyse_element`.

I can see a couple of options here. One is to make a set of well-defined exceptions available to these selectors, each of which indicates a type of failure that mtriage can then deal with appropriately. For example:
* `ElementAnalysisFailedSkipError` - something went wrong, and mtriage should just move to the next element. This could also operate as a catch-all, i.e. if other exceptions are thrown, this is the default behaviour.
* `ElementAnalysisFailedRetryError` - something went wrong, but mtriage should restart analysis on the element. Should probably have parameters, such as max number of retries, so that mtriage doesn't get stuck in an infinite loop.

Another option is to expect that selectors/analysers implement error handling themselves. In other words, a well-built module should _never throw an error_. `retrieve_element` and `analyse_element` would instead relay information about the state of a process only ever as  a return value, which could be an enum that defines similar states.

Running errors in modules that are unhandled:
* operating on an element with incorrect media in all modules.
* operating on video file without audio in `extract_audio`.
* failed download in `youtube`
* failed generation of any images in `frames`, as this causes errors down the line.

**Comment by breezykermo** [comment]
@samludford what do you think? @RaphiePS looping you in here as well as this design decision may bear on parallelisation.

**Comment by RaphiePS** [comment]
My WIP parallelisation/resumable-work system uses a SQLite database to keep track of which tasks have been `completed` and which are `pending`. It'd be really easy to add a third state (`failed`) and a retry counter. The exact logic around this behavior - what sort of errors should be thrown, how many times to retry, whether to retry at all - shouldn't affect things on my end too much. 

I really like being able to specify whether a task should be retried or skipped, but I'd also add a command-line option or in-code flag that makes uncaught exceptions crash the process. That would make it much easier to debug while developing a module, and then you could turn it off when you're confident you've eliminated unexpected errors.

**Comment by samludford** [comment]
I think the mechanics of retrying and skipping should certainly live in mtriage, but a certain amount of error handling logic will always reside in the module (e.g. deciding whether an error from a 3rd party service should provoke a retry or a skip), so as far as distribution of the logic goes I don't think there's much in it. 

The key difference between the two strategies seems to be how they structure error logging. If we return an enum value then error logging should be performed in modules via calls to `self.logger` before returning. On the other hand, if we raise well-defined exceptions the module can pass a description of the error (e.g. error message from youtube API, or ffmpeg) up to mtriage at the same time as requesting a retry, which can then be logged in a consistent way by the framework. I'm leaning towards this latter option as it seems cleaner, particularly when multiple modules are used in combination. 

On the point about crashing the process - I don't think there should be option for a module to explicitly raise a fatal error on an element operation, because elements should be independent of each other (when dependencies exist between data they should be grouped into a single element). So I think that the default behaviour should be to skip an element if it fails, however completely agree with @RaphiePS that it would be great to be able to turn this off for dev purposes.

**Comment by breezykermo** [comment]
Good points, let's go with typed errors that are made available to modules, one of which implies that analysis/retrieval should be restarted. Unrecognisied errors will default to mtriage logging a descriptive error and skipping the element, with a flag for development that breaks analysis at errors.

We can also use this issue as an opportunity to develop slightly more robust analyser logging. Currently Analyser.loggers write to an `analyser_logs.txt` file that sits in the top layer of each selector folder. 'User' logs, as in those generated using `self.logger` in modules, should probably at least be nested within the relevant `derived` folder. Element-wise analysis that fails or errors should be foregrounded in this log structure somehow.

@samludford, have a go at this if you have a moment this week, otherwise I'll take a stab early next.

**Comment by samludford** [comment]
I've made a start on this and it's raising some questions about the analyser logs:

Currently `pre_analyse` is called once before any elements are analysed, and `post_analyse` is called after they have all been analysed, including when the elements are drawn from multiple selectors. This means logs arising from calls made to `self.logger` within `pre_ `/`post_analyse` have no particular derived folder they are associated with.

Options:
* put non-selector-specific logs in the top level folder and selector-specific logs in the respective derived folder (this seems messy to me - will make it difficult to follow the whole process).
* keep all analyser logs in the top level folder but provide more info about each log's origin than is currently there. (e.g. [analyser name] : [element ID] : [log])
* refactor the analyser ABC so that `pre_` and `post_analyse` are called selector-wise. Then the analyser would go through a complete lifecycle on each selector and logs could happily live in their respective derived folders without any need for top-level analyser logs.

Any thoughts @breezykermo ?

As for foregrounding the error logs, I would lean towards putting them in the same files as other logs and highlight them with formatting (e.g. a line break above and below an error in log file, appearing in red when printed to the terminal), rather than put them in separate files where they lose context.

**Comment by breezykermo** [comment]
Hmm I see. The reason that I don't like having all logs in the top level is that, as you run more analysis and derive new elements, the logs are essentially just appended to that one file and so it begins to lose sense.

Could we go for your option 2, but contain the logs of each analysis to a separate file? i.e., there is an `analyser_logs` _folder_ that lives at the top level, in which a new file is created each time an analyser (or meta analyser composition) is invoked. Prepending each line of logs with context as you say is a great idea, as it will make the logs more descriptive in the case of meta analysers.
